### ISSUE TITLE
Upcoming driver API change

### ISSUE THREAD

**Issue by CarsonF** [enisdenjo/graphql-yoga-nestjs#84]
Hey I was just looking around and found this repo. I recently refactored the driver methods so that schema generation is independent of driver start/stop.
https://github.com/nestjs/graphql/pull/2435

It hasn't been released yet, but I wanted to give you a heads up as it would be a breaking change for you.

**Comment by enisdenjo** [comment]
Oh, thanks for the heads up! I'll take a look. 😄

**Comment by CarsonF** [comment]
Looks like it got released as v11.
That may make it easier for you to do a major release as well dropping support for v10.

**Comment by enisdenjo** [comment]
Awesome, thank you! I hope to release the v1 of Yoga + Nest driver this week. 😄

**Comment by enisdenjo** [comment]
Closed in https://github.com/dotansimha/graphql-yoga/pull/2525.
